<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe" novalidate action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <input name="email" type="email" id="newsletter" class="newsletterEmail" placeholder="<?= $block->escapeHtml(__('Mail')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" />
                    </label>
                </div>
            </div>
            <div></div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Suscribirse')) ?>" type="submit" aria-label="Subscribe" id="newsletterButton">
                    <span><?= $block->escapeHtml(__('Suscribirse')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
<script>
    require([
        "jquery"
    ], function($) {
        $(document).ready(function() {
            $("#newsletterButton").click(function() {
                var settings = {
                    "async": true,
                    "crossDomain": true,
                    "url": "https://events.woowup.com/events/users",
                    "type": "POST",
                    "headers": {
                        "cache-control": "no-cache",
                    },
                    "data": JSON.stringify({
                        "app": "jJ3tT1Z3B",
                        "email": $('input[class=newsletterEmail]').val(),
                        "tags": "footer,newsletter"
                    })
                }

                console.log($('input[class=newsletterEmail]').val());

                    $.ajax(settings).done(function(response) {
                        console.log("response");
                        console.log(response);
                    }).fail(function() {
                        alert("error");
                    });
                    // expected output: ReferenceError: nonExistentFunction is not defined
                    // Note - error messages will vary depending on browser
                console.log("afterAjax");
            });

        });
    });
</script>
