<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product-item-name">
    <span class="product bodega product-item-bodega">
        <?php $_getBodega = $product->getResource()->getAttribute('bodega'); ?>
        <?php echo $bodega = $_getBodega->getFrontend()->getValue($product); ?>
    </span>
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
    <span class="product varietal product-item-varietal">
    <?php $_getVarietal = $product->getResource()->getAttribute('varietal'); ?>
    <?php echo $varietal = $_getVarietal->getFrontend()->getValue($product); ?> </span>
</strong>
