stage:
    global:
        MIN_LOGGING_LEVEL: debug
        SCD_ON_DEMAND: true
    build:
        SKIP_SCD: false
        QUALITY_PATCHES:
            - MDVA-31307
            - MDVA-34330
        SCD_MATRIX:
            "Magento/backend":
                language:
                    - en_US
                    - es_AR
            "vys/pearl_redesign_child":
                language:
                    - es_AR
    deploy:
        SKIP_SCD: true


            # # Disable Codazon themes
            # "Codazon/theme-fastest_baby_kid/default": []
            # "Codazon/theme-fastest_bigmarket/default": []
            # "Codazon/theme-fastest_car/default": []
            # "Codazon/theme-fastest_drug_pharmacy/default": []
            # "Codazon/theme-fastest_ellyana/default": []
            # "Codazon/theme-fastest_food_drink/default": []
            # "Codazon/theme-fastest_furniture/default": []
            # "Codazon/theme-fastest_grocery_gourmet/default": []
            # "Codazon/theme-fastest_handbag/default": []
            # "Codazon/theme-fastest_hightech/default": []
            # "Codazon/theme-fastest_jewelry/default": []
            # "Codazon/theme-fastest_mechanic_tools/default": []

        MYSQL_USE_SLAVE_CONNECTION: true
        CRON_CONSUMERS_RUNNER:
            cron_run: true

        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'

    post-deploy:
        WARM_UP_PAGES:
            - 'store-page:/index.php:penaflor'
            - 'store-page:/customer/account/login/:ventainstitucional'
            - 'store-page:/customer/account/login/:tac'

