<div class="entrega-cont">
	<div class="text-entrega">
		<img src="<?php echo $this->getViewFileUrl('images/envio_icon.png'); ?>" />
		<span>¡RETIRÁ TU MOTO DE NUESTRAS SUCURSALES DE TODO EL PAÍS!</span>	
	</div>	
	<div class="text-entrega">
		<img src="<?php echo $this->getViewFileUrl('images/cc-icon.png'); ?>" />
		<span>NO TE PIERDAS LAS PROMOS Y CRÉDITOS BANCARIOS</span>	
	</div>	
	<div class="text-entrega patente">
		<img src="<?php echo $this->getViewFileUrl('images/cc-icon.png'); ?>" />
		<span>NO INCLUYE COSTO DE PATENTAMIENTO</span>	
		<a href="#">más info +</a>
	</div>	
	<div class="text-entrega puntos-entrega">
	Consultá nuestros puntos de entrega en todo el país <a href="#">aquí</a>
	</div>
</div>