<?php
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var $_helper \Magento\Catalog\Helper\Output
 * @var $_optionHelper \Codazon\ThemeOptions\Helper\Data
 * @var $_mobileHelper \Codazon\ThemeOptions\Helper\Mobile
 */
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_optionHelper = $this->helper('Codazon\ThemeOptions\Helper\Data');
$_mobileHelper = $this->helper('Codazon\ThemeOptions\Helper\Mobile');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $showHover = $_optionHelper->getConfig('general_section/category_view/hover_product_effect');
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $image_hover = 'category_page_grid_hover';
        $showDescription = $_optionHelper->getConfig('general_section/category_view/show_short_description');
        $showCompareWishlist = $_optionHelper->getConfig('general_section/category_view/show_action');
        $showReviewRating = $_optionHelper->getConfig('general_section/category_view/review_rating_star');
        $pageColumn = $_optionHelper->getPageColumns();
        switch($pageColumn){
            case '3columns':
                $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_3col');
                $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_3col');
                break;
            case '1column':
                $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_1col');
                $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_1col');
                break;
            case '2columns':
                $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_2col');
                $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_2col');
                break;
            default:
                $columnsDeskClass = 'desktop_'.$_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_2col');
                $columnsTabClass = 'tablet_'.$_optionHelper->getConfig('general_section/category_view/category_tablet_view/product_row_tablet_2col');
                break;
        }
        //echo $_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_2col');
        //echo $_optionHelper->getConfig('general_section/category_view/category_desktop_view/product_row_desk_1col');
        //echo $columnsDeskClass;
        $columnsMobileClass = 'mobile_'.$_optionHelper->getConfig('general_section/category_view/category_mobile_view/product_row_mobile');
        if(!$_mobileHelper->isMobile()){
            // desktop
            $columnsClass = $columnsDeskClass;
        }else if($_mobileHelper->isTablet()){
            // tablet
            $columnsClass = $columnsTabClass;
        }else{
            // mobile, not tablet
            $columnsClass = $columnsMobileClass;
        }
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $image_hover = 'category_page_list_hover';
        $showDescription = $_optionHelper->getConfig('general_section/category_view/show_short_description');;
        $showCompareWishlist = $_optionHelper->getConfig('general_section/category_view/show_action');
        $showReviewRating = $_optionHelper->getConfig('general_section/category_view/review_rating_star');
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $columnsClass = 'desk_1';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="<?php echo $columnsClass ?>" id="category-products-grid">
            <ol class="products list items product-items same-height">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <div class="cdz-hover-section">
                            <div class="cdz-product-top">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                $productHoverImage = $block->getImage($_product, $image_hover);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <span class="main-image">
                                        <?php echo $productImage->toHtml(); ?>
                                    </span>
                                    <span class="hover-image">
                                        <?php echo $productHoverImage->toHtml(); ?>
                                    </span>
                                </a>
                            </div>
                            <!--wishlist-->
                            <div class="cdz-product-wishlist show-tooltip">
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showCompareWishlist): ?>
                                    <a href="#"
                                       class="action towishlist"
                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                       data-action="add-to-wishlist"
                                       role="button">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="product details product-item-details">
                            <?php if ($_product->hasData('brand')): ?>
                                <p style="color:black"><strong><?php echo $_product->getAttributeText('brand'); ?></strong></p>
                            <?php elseif ($_product->hasData('linea2')): ?>
                                <p style="color:black"><strong><?php echo $_product->getAttributeText('linea2'); ?></strong></p>
                            <?php endif; ?>
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>

                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <a href="http://www.yuhmak.local/18k-italian-yellow-gold.html">
                                        <button type="submit" title="Add to Cart" class="action tocart primary">
                                            <span>Ver Moto</span>
                                        </button>
                                    </a>
                                </div>
                            </div>
                            <div class="product-item-inner">
                                <!--<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>

                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    </div>
                                </div>-->
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
    <?php if ($block->getMode() == 'grid'): ?>
        <script type="text/javascript">
            require(['jquery'],function($){
                function setClass(){
                    var widthWindow = $(window).width();
                    var list = $('#category-products-grid');
                    if(widthWindow > 1200)
                        list.removeClass().addClass('<?php echo $columnsDeskClass ?>');
                    else if(widthWindow > 768)
                        list.removeClass().addClass('<?php echo $columnsTabClass ?>');
                    else
                        list.removeClass().addClass('<?php echo $columnsMobileClass ?>');
                }
                $(window).on('resize',function(){
                    setClass();
                });
                setClass();
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
