<?php
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_weltpixelHelper = $this->helper('WeltPixel\CategoryPage\Helper\Data');
$displayReviews = $_weltpixelHelper->displayReviews();
$displayWishlist = $_weltpixelHelper->displayAddToWishlist();
$displayCompare = $_weltpixelHelper->displayAddToCompare();
$displayAddToCart = $_weltpixelHelper->displayAddToCart();
$alignAddToCart = $_weltpixelHelper->alignAddToCart();
$displaySwatches = $_weltpixelHelper->displaySwatches();
$hoverAnimation = $_weltpixelHelper->getCategoryPageProductsHoverAnimation();

/** WeltPixel_GoogleTagManager  */
$gtmHelper = null;
$gtmHelperClassName = '';
try {
    $gtmHelper = $this->helper('WeltPixel\GA4\Helper\Data');
    $gtmHelperClassName = 'WeltPixel\GA4\Helper\Data';
} catch (\Exception $ex) {
}
try {
    $gtmHelper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');
    $gtmHelperClassName = 'WeltPixel\GoogleTagManager\Helper\Data';
} catch (\Exception $ex) {
}
?>

<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */
                                    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
                                echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info hover-animation-<?php /* @escapeNotVerified */ echo $hoverAnimation; ?>" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image 
                    ?>
                    <?php if ($viewMode == 'grid') : ?>
                        <div class="product_image">
                        <?php endif; ?>
                        <a data-wpproductlabel="1" data-product-id="<?php echo $_product->getId() ?>" <?php if ($gtmHelper && $gtmHelper->isProductClickTrackingEnabled()) :
                                                                                                            echo $this->helper($gtmHelperClassName)->addProductClick($_product, $iterator - 1);
                                                                                                        endif; ?> href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml() ?>
                        </a>
                        <?php if ($viewMode == 'grid' && (($displayWishlist != 0 && $displayWishlist != 5) || ($displayCompare != 0 && $displayCompare != 5))) : ?>
                            <div class="product actions product-item-actions">
                                <div class="actions-secondary"></div>
                            </div>
                        <?php endif; ?>
                        <?php if ($viewMode == 'grid') : ?>
                        </div>
                    <?php endif; ?>

                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-item-name">
                            <a <?php if ($gtmHelper && $gtmHelper->isProductClickTrackingEnabled()) :
                                    echo $this->helper($gtmHelperClassName)->addProductClick($_product, $iterator - 1);
                                endif; ?> class="product-item-link" href="<?php /* @escapeNotVerified */
                                                                        echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */
                                echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                        <!-- acá va la bodega -->
                        <span class="product bodega product-item-bodega">
                            <?php $_getBodega = $_product->getResource()->getAttribute('bodega'); ?>
                            <?php echo $bodega = $_getBodega->getFrontend()->getValue($_product); ?>
                        </span>
                        <br />
                        <!-- acá va el varietal -->
                        <span class="product varietal product-item-varietal">
                            <?php $_getVarietal = $_product->getResource()->getAttribute('varietal'); ?>
                            <?php echo $varietal = $_getVarietal->getFrontend()->getValue($_product); ?> </span>
                        <br />
                        <?php
                        $notas_de_cata = $_product->getResource()->getAttribute('notas_de_cata')->getFrontend()->getValue($_product);

                        
                        ?>

                        <?php if ($viewMode == 'list'): ?>
                            <div class="notas-de-cata">
                            <?php if (!is_null($notas_de_cata)): ?>
                            <div class="notas_de_cata separador notas_de_cata_categoria">
                                <span class="titulo_category">NOTAS DE CATA</span>
                                <p class="texto">
                                    <?php  echo $notas_de_cata;?>
                                </p>
                            </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        
                        <div class="price-and-buttons">
                        <div>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

                        <?php if ($viewMode == 'list'): ?>
                            <?php if ($_product->getIsSalable()): ?>
                            <div style="display: inline-flex;">
                                    <a href="#" class="action towishlist whishlist_position_<?php /* @escapeNotVerified */
                                        echo $displayWishlist; ?>" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                        </a>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                                                    echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                                                                            echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                                            echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                                                                                                echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                </button>
                                        </form>
                                    <div class="actions-secondary">
                                        <div class="secondary-addto-links actions-secondary">
                                            <a href="#"  class="action toquickview" title="Vista rápida">
                                                <span></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                </div>
                            <?php else: ?>
                                <div style="display: inline-flex;">
                                    <a href="#" class="action towishlist whishlist_position_<?php /* @escapeNotVerified */
                                        echo $displayWishlist; ?>" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                        </a>
                                    <button class="action tocart primary"
                                            style="text-transform: uppercase; background-color: grey; border-color: grey;"
                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Out of stock') ?>">
                                        <!-- <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span> -->
                                        <span> AGOTADO </span>
                                    </button>
                                    <div class="actions-secondary">
                                        <div class="secondary-addto-links actions-secondary">
                                            <a href="#"  class="action toquickview" title="Vista rápida">
                                                <span></span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <div class="detail" style="text-align: center; opacity:50%; font-size:.8em;">
                                <p style="margin: 10px 0 0;">Precio por botella</p>
                                <p style="margin: 0 0 1em; padding-bottom: 1em;">Compra mínima 6 botellas</p>
                            </div>
                            </div>
                            </div>
                        <?php endif; ?>






                        <?php /* @escapeNotVerified */ echo $block->getProductDetailsHtml($_product); ?>

                        <?php $hoverShow = ($displayAddToCart == 4 || $displayAddToCart == 5 || $displayAddToCart == 0 || $displayWishlist == 5 || $displayWishlist == 0 || $displayCompare == 5 || $displayCompare == 0) ? 'hoverShow' : '';   ?>

                        <div class="product-item-inner <?php echo /* @escapeNotVerified */ $hoverShow; ?>">

                            <div class="product-item-inner-hide"></div>
                            <div class="product actions product-item-actions <?php echo isset($alignAddToCart) == 'center' ? ' ' . $alignAddToCart : ''; ?>" <?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary" <?php /* @escapeNotVerified */
                                                                echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($displayAddToCart != 0 && $_product->isSaleable()) : ?>
                                        <div class="product-action-add addtocart_position_<?php /* @escapeNotVerified */
                                                                        echo $displayAddToCart;
                                                                        echo isset($alignAddToCart) ? ' ' . $alignAddToCart : ''; ?>">
                                            
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <a href="#" class="action towishlist whishlist_position_<?php /* @escapeNotVerified */
                                                                                                echo $displayWishlist; ?>" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
                                                                                                                                                                                                                            echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                            <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Wish List') ?></span>
                                        </a>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                                                                    echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */
                                                                                            echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                                            echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */
                                                                                                echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit" title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                            <div class="actions-secondary">
                                                <div class="secondary-addto-links actions-secondary">
                                                    <a href="#"  class="action toquickview" title="Vista rápida"">
                                                        <span></span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="detail"
                                            style="text-align: center; opacity:50%; font-size:.8em;">
                                            <p style="margin: 10px 0 0;">Precio por botella</p>
                                            <p style="margin: 0 0 1em; padding-bottom: 1em;">Compra mínima 6 botellas</p>
                                        </div>

                                    <?php elseif ($displayAddToCart != 0) : ?>
                                        <div class="addtocart_position_<?php /* @escapeNotVerified */
                                                                        echo $displayAddToCart;
                                                                        echo $alignAddToCart; ?>">
                                            <?php if ($_product->getIsSalable()) : ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                                    echo __('In stock') ?></span></div>
                                            <?php else : ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                                        echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary" <?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($displayWishlist != 0 && $this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                        <a href="#" class="action towishlist whishlist_position_<?php /* @escapeNotVerified */
                                                                                                echo $displayWishlist; ?>" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */
                                                                                                                                                                                                                            echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                            <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                    <?php if ($displayCompare != 0) : ?>
                                        <a href="#" class="action tocompare compare_position_<?php /* @escapeNotVerified */
                                                                                                echo $displayCompare; ?>" title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" data-post='<?php /* @escapeNotVerified */
                                                                                                                                                                                                                        echo $compareHelper->getPostDataParams($_product); ?>' role="button">
                                            <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Compare') ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription) : ?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */
                                                echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                                                                echo $_productNameStripped ?>" class="action more"><?php /* @escapeNotVerified */
                                                                                        echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>

                        <?php if ($viewMode == 'grid'): ?>
                            <?php if ($_product->getIsSalable()): ?>
                                <div></div>
                                <?php else: ?>
                                    <div style="display: inline-flex;">
                                        <a href="#" class="action towishlist whishlist_position_<?php /* @escapeNotVerified */
                                            echo $displayWishlist; ?>" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist" role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <button class="action tocart primary"
                                                style="text-transform: uppercase; background-color: grey; border-color: grey;"
                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Out of stock') ?>">
                                            <!-- <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span> -->
                                            <span> AGOTADO </span>
                                        </button>
                                        <div class="actions-secondary">
                                            <div class="secondary-addto-links actions-secondary">
                                                <a href="#"  class="action toquickview" title="Vista rápida">
                                                    <span></span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                            <?php endif; ?>
                        <?php endif; ?>

                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
        <script>
            require(['jquery', 'WeltPixel_CategoryPage/js/productItemActions'],
                function($, CategoryPage) {
                    window.actions = {
                        displayWishlist: '<?php /* @escapeNotVerified */ echo $displayWishlist; ?>',
                        displayCompare: '<?php /* @escapeNotVerified */ echo $displayCompare; ?>',
                        displayAddToCart: '<?php /* @escapeNotVerified */ echo $displayAddToCart; ?>',
                        displaySwatches: '<?php /* @escapeNotVerified */ echo $displaySwatches; ?>'
                    };
                    CategoryPage.actions();
                });
        </script>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>