<?php
use Magento\Framework\App\Action\Action;
?>
<script>
    require(['jquery','js/home-scripts']);
</script>
<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
/** @var \Lyracons\QtyIncrement\Helper\Data $itemHelper */
$itemHelper = $this->helper('Lyracons\QtyIncrement\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    // Se usa MD5 para evitar colisiones de nombres. No es un tema de seguridad. Viene así de Codazon
    // phpcs:ignore Magento2.Security.InsecureFunction
    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php if ($title):?>
		<div class="block-title">
		    <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
		</div>
		<?php endif ?>
		<div class="products-filters">
			<div class="attribute-selector">
				<span>Buscá nuestros vinos por:</span>
				<a href="#" class="toggle-attribute toggle-varietal">Varietal <i class="fa fa-angle-down" aria-hidden="true"></i></a>
				<a href="#" class="toggle-attribute toggle-vinedo">Viñedo <i class="fa fa-angle-down" aria-hidden="true"></i></a>
			</div>
			<div class="attribute-items attribute-varietal">
				<ul>
					<li class="attr-item" data-attribute-option="Blend">
						<span class="attr-check"></span>
						<span class="attr-title">Blend</span>
					</li>
					<li class="attr-item" data-attribute-option="Cabernet Sauvignon">
						<span class="attr-check"></span>
						<span class="attr-title">Cabernet Sauvignon</span>
					</li>
					<li class="attr-item" data-attribute-option="Chardonnay">
						<span class="attr-check"></span>
						<span class="attr-title">Chardonnay</span>
					</li>
					<li class="attr-item" data-attribute-option="Malbec">
						<span class="attr-check"></span>
						<span class="attr-title">Malbec</span>
					</li>
					<li class="attr-item" data-attribute-option="Pinot Noir">
						<span class="attr-check"></span>
						<span class="attr-title">Pinot Noir</span>
					</li>

					<li class="attr-item" data-attribute-option="Rosado">
						<span class="attr-check"></span>
						<span class="attr-title">Rosado</span>
					</li>
				</ul>
			</div>
			<div class="attribute-items attribute-vinedo" style="display: none;">
				<ul>
					<li class="attr-item" data-attribute-option="Cruz de Piedra">
						<span class="attr-check"></span>
						<span class="attr-title">Cruz de Piedra</span>
					</li>
					<li class="attr-item" data-attribute-option="Finca La Mascota">
						<span class="attr-check"></span>
						<span class="attr-title">Finca La Mascota</span>
					</li>
					<li class="attr-item" data-attribute-option="Valle de Uco">
						<span class="attr-check"></span>
						<span class="attr-title">Valle de Uco</span>
					</li>
				</ul>
			</div>
		</div>
		<div class="block-content <?php echo $classid ?>">
			<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
				<?php $iterator = 1; ?>
				<ol class="products list items product-items">
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product):
				    $_getVarietal = $_product->getResource()->getAttribute('varietal');
				    $varietal = $_getVarietal->getFrontend()->getValue($_product);

				    $_getVinedo = $_product->getResource()->getAttribute('vi_edo');
				    $vinedo = $_getVinedo->getFrontend()->getValue($_product);

				    $varietalLabel = $_getVarietal->getStoreLabel();
				    $stock = "";
				    ?>
				    <?php if (!$_product->getIsSalable()){
				    		$stock = "no-stock";
				    	}
				    	?>
				        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item '.$stock.'" data-varietal="'.$varietal.'" data-vinedo="'.$vinedo.'">' : '</li><li class="item product product-item '.$stock.'" data-varietal="'.$varietal.'" data-vinedo="'.$vinedo.'">' ?>
				        <div class="product-item-info" data-container="product-grid">

				        	<?php
				        	    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
				        	?>
				        	<?php if($block->isShow('name')): ?>
				        	<strong class="product name product-item-name">
				        	    <a class="product-item-link"
				        	       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				        	        <?php /* @escapeNotVerified */
				        	        $prod_name = str_replace(".", "</br>", $_helper->productAttribute($_product, $_product->getName(), 'name'));
				        	        echo $prod_name;

				        	        ?>
				        	    </a>
				        	</strong>
				        	<?php endif ?>

				            <?php
				            $productImage = $block->getImage($_product, $image);
				            if ($pos != null) {
				                $position = ' style="left:' . $productImage->getWidth() . 'px;'
				                    . 'top:' . $productImage->getHeight() . 'px;"';
				            }
				            ?>

				            <?php // Product Image ?>
				            <div class="image-wrapper">
					            <?php if($block->isShow('thumb')): ?>
					            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
					                <?php echo $productImage->toHtml(); ?>
					            </a>
					            <?php endif ?>
							</div>
				            <div class="product details product-item-details">
				                <?php if($block->isShow('review')): ?>
				                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
				                <?php endif ?>
				                <?php if($block->isShow('price')): ?>
				                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
				                <?php endif ?>
				                <?php if (!$_product->getIsSalable()): ?>
				                	<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
				                <?php endif;?>
				                <div class="product-qty">
				                    <?php /* @escapeNotVerified */ echo __('Compra mínima de %1 botellas', $itemHelper->getQtyIncrementsByProduct($_product)) ?>
				                </div>
				                <?php echo $block->getProductDetailsHtml($_product); ?>

				                <div class="product-item-inner">
				                <?php if($block->isShow('description')): ?>
				                    <div class="product description product-item-description">
				                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
				                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
				                    </div>
				                <?php endif; ?>
				                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
				                    	<?php if($block->isShow('addtocart')): ?>
				                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
				                            <?php if ($_product->isSaleable()): ?>
				                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
				                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
				                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
				                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
				                                    <input type="hidden" name="qty" value="<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>" />
				                                    <?php echo $block->getBlockHtml('formkey')?>
				                                    <button type="submit"
				                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
				                                            class="action tocart primary">
				                                            <i class="icon-cart"></i>
				                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
				                                    </button>
				                                </form>
				                            <?php endif; ?>
				                        </div>
				                        <?php endif ?>
				                        <?php if($block->isShow('addto')): ?>
				                        <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
				                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
				                                <a href="#"
				                                   class="action towishlist"
				                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
				                                   data-action="add-to-wishlist"
				                                   role="button">
				                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
				                                </a>
				                            <?php endif; ?>
				                            <?php
				                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
				                            ?>
				                            <a href="#"
				                               class="action tocompare"
				                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				                               role="button">
				                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
				                            </a>
				                        </div>
				                        <?php endif ?>
				                    </div>
				                </div>
				            </div>
				        </div>
				        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				    <?php endforeach; ?>
				</ol>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
		</div>
        <script type="text/javascript">
            // require the require function
            require( [ 'require', 'jquery', 'isotope' ],
                function( require, $, Isotope ) {
                    // require jquery-bridget, it's included in isotope.pkgd.js
                    require( [ 'jquery-bridget/jquery-bridget' ],
                        function( jQueryBridget ) {
                            jQueryBridget( 'isotope', Isotope, $ );
                            if (typeof window.loadedHomeFilterEvents != 'undefined')
                                return;
                            $('ol.product-items').isotope({
                                itemSelector: 'li.item',
                                layoutMode: 'fitRowsCentered'
                            });
                            //Events
                            $(document).on("click", ".attr-item", function(){
                                var $btn = $(this);
                                //toggle button class
                                if ($btn.hasClass('checked')) {
                                    $btn.removeClass('checked');
                                }
                                else {
                                    $btn.addClass('checked');
                                }
                                //find active Filters
                                var filters = [],
                                    $parentContainer = $btn.parents('.attribute-items').first();
                                $parentContainer.find('li.attr-item.checked').each(function() {
                                    filters.push($(this).data('attribute-option'));
                                });
                                //filter
                                $('ol.product-items').isotope({
                                    layoutMode: 'fitRowsCentered',
                                    filter: function() {
                                        //has no filter
                                        if (filters.length == 0) {
                                            return true;
                                        }
                                        //has Filter
                                        else {
                                            if ($parentContainer.hasClass('attribute-varietal')) {
                                                return filters.indexOf($(this).data('varietal')) == -1 ? false : true;
                                            }
                                            else if ($parentContainer.hasClass('attribute-vinedo')) {
                                                return filters.indexOf($(this).data('vinedo')) == -1 ? false : true;
                                            }
                                        }
                                    }
                                });
                            });
                            $(document).on("click", ".toggle-attribute", function(e){
                                e.preventDefault();
                                if($(this).hasClass("toggle-varietal")){
                                    $(".attribute-varietal").slideDown();
                                    $(".attribute-vinedo").slideUp();
                                }else{
                                    $(".attribute-varietal").slideUp();
                                    $(".attribute-vinedo").slideDown();
                                }
                            });
                            window.loadedHomeFilterEvents = true;
                        }
                    );
                });
        </script>
	</div>
	<?php if($block->getData('show_slider')): ?>
	<script type="text/javascript">
		require(['jquery','Codazon_ProductFilter/owlcarousel/owl.carousel','domReady!'],function($){
		        var owl = $('.<?php echo $classid ?> .product-items');
		        if(owl.length){
		            owl.owlCarousel();
		        }
		    });
	</script>
    <?php endif ?>
<?php endif; ?>
