<div class="info-bodegas">
    <div class="text-container-bodegas">
        <h4 class="subtitle">Acerca de la Bodega</h4>
        <h2 class="title">Navarro correas</h2>
        <div>
            <p>Dedicados a la vitivinicultura desde 1798. Vivimos el vino desda el
            terror, y es en Finca Agrelo, al pie de la Cordillera de los Andes
            donde cada uno de nuestros vinos se concibe con la filosofía y el
            espíritu único que nos legó Don Juan de Dios Correas; quien en su
            afán incansable por superarse supo hacer perdurar su legado a
            través de las generaciones:</p>
            <p>"Nuestra Tradición es hacer siempre un vino Mejor"</p>
        </div>
    </div>
    <div class="img-container-bodegas">
        <img src="media/wysiwyg/vysRedesign/navarrocorreasbodega.jpg"/>
    </div>
</div>

<style>
    @media (max-width: 599px) {
    .info-bodegas {
        display: block !important;
    }

    .text-container-bodegas {
        width: auto !important;
        padding: 0 !important;
    }

    }
    .info-bodegas {
        display: flex;
        background-color: #F4F4F4;
    }

    .text-container-bodegas {
        width: 80%;
        align-self: center;
        text-align: center; 
        padding: 0px 50px 0px 50px;
    }

    .title, .subtitle {
        font-weight: 600;
    }

    .title {
        color: #D4A22C;
    }

</style>