<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div class="icon-container">
    <a><img class="icon-header" src="media/wysiwyg/vysRedesign/Icon_feather-heart.png" /><a>
    <a><img class="icon-header-account" src="media/wysiwyg/vysRedesign/Componente_82_15.png" /><a>
    <a href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>" ><img class="icon-header" src="media/wysiwyg/vysRedesign/Carrito_Penaflor.png" /><a>
        
</div>

<style>
    .icon-container {
        float: right;
    }

    .icon-header {
        width: 25px;
        margin-right: 10px;
    }

    .icon-header-account {
        width: 22px;
        margin-right: 10px;
    }

</style>