<?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

/** @var $itemHelper Lyracons\QtyIncrement\Helper\Data */
$itemHelper = $this->helper('Lyracons\QtyIncrement\Helper\Data');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Comprar'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
				<div class="qty-minus"> <a class="btn-qty minus fa fa-angle-down" href="#"></a></div>
				<div class="qty-input">
						<input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $itemHelper->getQtyIncrementsByProduct($_product); ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
				</div>
				<div class="qty-plus"> <a class="btn-qty plus fa fa-angle-up" href="#"></a></div>
            </div>
        </div>
		 <script type="text/javascript">
		require(['jquery','domReady!'],function($){
			$(".btn-qty").click(function (event) {
				var $button = $(this);
				var oldValue = $button.closest('.control').find("input#qty").val();
                var defaultValue = parseFloat(<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>);
                if ($button.hasClass('plus')) {
                    var newVal = parseFloat(oldValue) + parseFloat(<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>);
                } else {
                    if (oldValue > defaultValue) {
                        var newVal = parseFloat(oldValue) - <?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>;
                    } else {
                        newVal = defaultValue;
                    }
                }

				$button.closest('.control').find("input#qty").val(newVal);
				event.preventDefault();
			});

		});
        </script>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>

    <div class="sale-condition">
        <p>
            <?php /* @escapeNotVerified */ echo __('El precio informado es por botella.'); ?><br>
            <?php /* @escapeNotVerified */ echo __('La unidad de compra mínima son %1 botellas.', $itemHelper->getQtyIncrementsByProduct($_product));?>
        </p>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Codazon_AjaxCartPro/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>
