<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>

<div class="newlogin-confirmation">
    <div class="result error">
        <span class="icon icon-error"></span>
        <h4 class="title">Parece que el Email/DNI ya está asociado a un usuario en nuestro sistema</h4>
        <p style="text-align: center">
            <?= $block->escapeHtml(
            __('There is already an account with this email address. If you are sure that it is your email address, <a href="%1">click here</a> to get your password and access your account.', $block->getUrl("customer/account/forgotpassword"))
            , ['a']); ?>
        </p>
    </div>
</div>
