<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
use Magento\Framework\App\Action\Action;
?>

<?php

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $image_hover = 'related_products_list_hover';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = 0;//$block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $image_hover = 'related_products_list_hover';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $image_hover = 'upsell_products_list_hover';
            $title = __('Most popular products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $image_hover = 'upsell_products_list_hover';
            $title = __('Most popular products');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $image_hover = 'cart_cross_sell_products_hover';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $image_hover = 'cart_cross_sell_products_hover';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $image_hover = 'new_products_content_widget_grid_hover';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="related-upsell-crossell block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol class="products list items product-items owl-carousel">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                	<div class="cdz-hover-section">
						<div class="cdz-product-top">
						<?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
						<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
							<span class="main-image">
								<?php echo $block->getImage($_item, $image)->toHtml(); ?>
							</span>

						</a>
						</div>
						<?php if ($showWishlist || $showCompare): ?>
                        <div class="product actions product-item-actions cdz-product-wishlist show-tooltip">                	                                       
							<?php if ($showWishlist || $showCompare): ?>
								<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
										<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wishlist') ?>">
											<span><?php /* @escapeNotVerified */ echo __('Add to Wishlist') ?></span>
										</a>
									<?php endif; ?>
									<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<a href="#" class="action tocompare show-tooltip"
										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
										   data-role="add-to-links"
										   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
											<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
										</a>
									<?php endif; ?>
								</div>
							<?php endif; ?>
						</div>
						<?php endif; ?>
                            
                    </div>
						<div class="product details product-item-details">
							<strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
								<?php echo $block->escapeHtml($_item->getName()) ?></a>
							</strong>

                            <?php if($_item->hasData('varietal')): ?>
                                <p class="varietal"><strong><?php echo $_item->getAttributeText('varietal'); ?></strong></p>
                            <?php endif; ?>

                            <?php if($_item->hasData('presentacion_ml')): ?>
                                <p class="presentacion"><strong><?php echo $_item->getAttributeText('presentacion_ml'); ?></strong></p>
                            <?php endif; ?>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>
                        </div>
                    <div class="product actions product-item-actions">
                        <div class="actions-primary">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('View More') ?>" class="action tocart primary">
                                    <span><?php /* @escapeNotVerified */ echo __('View More') ?></span>
                                </button>
                            </a>
                        </div>
                    </div>  
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
 <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
<?php endif; ?>
<?php 
	$itemSlider = 4;
	if($type == 'crosssell' || $type == 'crosssell-rule'){
		$itemSlider = $itemSlider - 1;
	}
?>
<script type="text/javascript">
require(['jquery','cdz_slider'],function($){
	if($('.related-upsell-crossell .products-<?php /* @escapeNotVerified */ echo $type; ?> .product-items').length)
	{
		$('.related-upsell-crossell .products-<?php /* @escapeNotVerified */ echo $type; ?> .product-items').addClass('owl-carousel').parent().addClass('product-style02');
		$('.related-upsell-crossell .products-<?php /* @escapeNotVerified */ echo $type; ?> .product-items').owlCarousel({
			items: <?php echo $itemSlider; ?>,
		    lazyLoad: false,
			loop: false,
			margin: 20,
			responsiveClass: true,
			nav: true,
			dots: false,
			rtl: ThemeOptions.rtl_layout == 1 ? true : false, 
			responsive:{
				0:{items: <?php echo ($itemSlider > 2)  ?>},
				480:{items:	<?php echo ($itemSlider > 2)   ?>},
				640:{items:	<?php echo ($itemSlider > 2)  ?>},
				768:{items:	<?php echo  ($itemSlider - 1) ?>},
				1200:{items: <?php echo $itemSlider ?>}			
			}
		});
	}
})
</script>
<?php endif;?>
