<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe" novalidate action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter" class="newsletterEmail" placeholder="<?= $block->escapeHtml(__('Ingresá tu email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}" />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" aria-label="Subscribe" id="newsletterButton">
                    <span><?= $block->escapeHtml(__('SUSCRIBIRME')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
<script>
    function validateEmail(email) {
        const re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(email);
    }
    require([
        "jquery"
    ], function($) {
        $(document).ready(function() {
            $("#newsletterButton").click(function() {
                let email = $("#newsletter").val();
                if (!validateEmail(email)) return;
                
                var settings = {
                    "async": true,
                    "crossDomain": true,
                    "url": "https://events.woowup.com/events/users",
                    "type": "POST",
                    "headers": {
                        "cache-control": "no-cache",
                    },
                    "data": JSON.stringify({
                        "app": "jJ3tT1Z3B",
                        "email": email,
                        "tags": "newsletter"
                    })
                }
                $.ajax(settings);
            });
        });
    });
</script>