<div class="footer">
	<div class="logo-footer">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('logofooter')->toHtml();?>
	</div>
	<div class="footer-links">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mascota-footer-links')->toHtml();?>
	</div>
	<div class="footer-social">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mascota-footer-social')->toHtml();?>
	</div>
	<div class="footer-copyright">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mascota-footer-copyright')->toHtml();?>
	</div>
	<div class="footer-brands">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mascota-footer-brands')->toHtml();?>
	</div>
</div>