<?php

use Magento\Catalog\Block\Product\ListProduct;
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * @var $block ListProduct
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
/** @var \Lyracons\QtyIncrement\Helper\Data $itemHelper */
$itemHelper = $this->helper('Lyracons\QtyIncrement\Helper\Data');

// Methods for checking if Salable Quantity <= 0
$objectManager = ObjectManager::getInstance();
$stockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
$getProductTypesBySkus = $objectManager->get('\Magento\InventoryCatalogApi\Model\GetProductTypesBySkusInterface');
$isSourceItemManagementAllowedForProductType =  $objectManager->get('\Magento\InventoryConfigurationApi\Model\IsSourceItemManagementAllowedForProductTypeInterface');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    // Se usa MD5 para evitar colisiones de nombres. No es un tema de seguridad. Viene así de Codazon
    // phpcs:ignore Magento2.Security.InsecureFunction
    $classid = md5(json_encode($block->getData()));
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content <?php echo $classid ?>">
            <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items owl-carousel">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                                $productImage = $block->getImage($_product, $image);
                                $productImage->setProduct($_product);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <div class="name-wrapper">
                                    <div class="bodega">
                                        <?php
                                            $_getBodega = $_product->getResource()->getAttribute('bodega');
                                            $bodega = $_getBodega->getFrontend()->getValue($_product);
                                            if($bodega != "No"){
                                                echo $bodega;
                                            }
                                        ?>
                                    </div>
                                    <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <?php if($block->isShow('name')): ?>
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link"
                                            href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                            </a>
                                        </strong>
                                    <?php endif ?>
                                </div>
                                <div class="product-actions-wrapper">
                                    <?php
                                        $_getVarietal = $_product->getResource()->getAttribute('varietal');
                                        $varietal = $_getVarietal->getFrontend()->getValue($_product);
                                        if($varietal != "No"){
                                            echo '<div class="varietal">';
                                            echo $varietal;
                                            echo '</div>';
                                        }
                                    ?>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                    <div class="min-qty">
                                        <?php /* @escapeNotVerified */ echo __('Compra mínima: %1 unid.', $itemHelper->getQtyIncrementsByProduct($_product)) ?>
                                    </div>
                                    <div class="product-inner-wrapper">
                                        <div class="product-item-inner">
                                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                                    <?php
                                                        /* to avoid exception on some product types when calling $stockState */
                                                        $productTypesBySkus = $getProductTypesBySkus->execute([$_product->getSku()]);
                                                        $productType = $productTypesBySkus[$_product->getSku()];
                                                        $sourceManagementAllowed = $isSourceItemManagementAllowedForProductType->execute($productType);
                                                        $saleQty = $sourceManagementAllowed ? $stockState->execute($_product->getSku(), 1) : null;
                                                    ?>
                                                    <?php if (!$sourceManagementAllowed || ($_product->isSaleable() && $saleQty > 0)): ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                            <input type="hidden" name="qty" value="<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>" />
                                                            <?php echo $block->getBlockHtml('formkey')?>
                                                            <button type="submit"
                                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                    class="action tocart primary">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if (!$sourceManagementAllowed || ($_product->getIsSaleable() && $saleQty > 0)): ?>
                                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="product-view-link">
                                            <a class="product-item-link"
                                            href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */ echo __('Ver detalle del producto') ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php
                                $recomender = $_product->getAttributeText('recomender');

                                if($recomender){
                                    echo '<div class="recomendador"> ';
                                        echo '<div class="recomendador-item"><img src="'.$this->getViewFileUrl("images/Trazado_1750.png").'" /></div>';
                                        echo '<div class="recomendador-item"><p>' . __('Recomendado por:') . ' </p>  ' .$recomender.'</div>';
                                    echo '</div>';
                                }
                            ?>
                        </div>
                        <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                    <?php endforeach; ?>
                </ol>
            </div>
            <?php echo $block->getToolbarHtml() ?>
            <?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {}
                    }
                }
                </script>
            <?php endif; ?>
        </div>
    </div>
    <?php if($block->getData('show_slider')): ?>
    <script type="text/javascript">
        require(['jquery','Codazon_ProductFilter/owlcarousel/owl.carousel','domReady!'],function($){
                var owl = $('.<?php echo $classid ?> .product-items');
                if(owl.length){
                    owl.owlCarousel({
                        items: 4,
                        margin: 10,
                        nav: true,
                        dots: false,
                        loop: true,
                        responsive : {
                            // breakpoint from 0 up
                            0 : {
                                items : 1,
                                dots: true,
                                nav: false,
                                stagePadding: 40,
                            },
                            // breakpoint from 768 up
                            768 : {
                                items : 3,
                            },
                            1175 : {
                                items : 4,
                            }
                        }
                    });
                }
            });
    </script>
<?php endif ?>
<?php endif; ?>
