<?php

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;
use Magento\Framework\App\ObjectManager;

?>

<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

// Methods for checking if Salable Quantity <= 0
$objectManager = ObjectManager::getInstance();
$stockState = $objectManager->get('\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface');
$getProductTypesBySkus = $objectManager->get('\Magento\InventoryCatalogApi\Model\GetProductTypesBySkusInterface');
$isSourceItemManagementAllowedForProductType =  $objectManager->get('\Magento\InventoryConfigurationApi\Model\IsSourceItemManagementAllowedForProductTypeInterface');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    $viewMode = 'slider';
    $image = 'category_page_grid';
    $image_hover = 'category_page_grid_hover';
    $showDescription = false;
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    $classid = $block->getBlockId();//uniqid();//md5(json_encode($block->getData()));
	
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $sliderItem = $block->getData('slider_item') ? $block->getData('slider_item') : 4;
    ?>
    <div class="block widget block-products-list product-style02 <?php /* @escapeNotVerified */ echo $viewMode; ?>">
		<?php if ($title):?>
		<div class="cdz-block-title">
		    <h2 class="b-title"><span><?php /* @escapeNotVerified */ echo $title; ?></span></h2>
		</div>
		<?php endif ?>
		<div class="block-content <?php echo $classid ?>">
			<div class="products products-grid wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
				<?php $iterator = 1; ?>
				<div class="products list items product-items <?php echo $block->getData('show_slider') ? 'cdz-slider' : '' ?>"
					<?php if($block->getData('show_slider')) : ?>
					<?php $slider_item =  ($block->getData('slider_item')) ?  $block->getData('slider_item') : 6 ?>
						data-items="<?php echo $slider_item ?>"
						data-items-0="2"
						data-items-480="2"
						data-items-768="<?php echo abs($slider_item-2) ?>"		            	
						data-items-1024="<?php echo abs($slider_item-1) ?>"	
						data-items-1280="<?php echo $slider_item ?>"
						data-items-1440="<?php echo $slider_item ?>"
						data-loop="false"
						data-margin="20"
						data-autoWidth="false"
					<?php endif; ?>
				>
				    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				    <?php foreach ($_productCollection as $_product): ?>
				        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
				        <div class="product-item-info" data-container="product-grid">
				        	<div class="cdz-hover-section">
					        	<div class="cdz-product-top">
						            <?php
						            $productImage = $block->getImage($_product, $image);
						            $productHoverImage = $block->getImage($_product, $image_hover);
						            if ($pos != null) {
						                $position = ' style="left:' . $productImage->getWidth() . 'px;'
						                    . 'top:' . $productImage->getHeight() . 'px;"';
						            }
						            ?>
						            <?php // Product Image ?>
						            <?php if($block->isShow('thumb')): ?>
						            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
						                <span class="main-image">
											<?php echo $productImage->toHtml(); ?>
										</span>
									</a>
						            <?php endif ?>
					        	</div>
				        	</div>
		                    <?php if($block->isShow('addto')): ?>
		                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
		                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
		                            <a href="#"
		                               class="action towishlist"
		                               title="<?php echo $block->escapeHtml(__('Agregar a Favoritos')); ?>"
		                               aria-label="<?php echo $block->escapeHtml(__('Agregar a Favoritos')); ?>"
		                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
		                               data-action="add-to-wishlist"
		                               role="button">
		                                <span><i class="fa fa-heart-o" aria-hidden="true"></i></span>
		                            </a>
		                        <?php endif; ?>
		                    </div>
				            <div class="product details product-item-details">
				                <?php
				                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
				                ?>
				                <?php if($block->isShow('name')): ?>
				                <strong class="product name product-item-name">
				                    <a class="product-item-link"
				                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
				                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				                    </a>
				                </strong>
				                    <p class="varietal">
				                <?php if($_product->hasData('varietal')): ?>
				                    	<strong><?php echo $_product->getAttributeText('varietal'); ?></strong>
				                <?php endif; ?>
				                    </p>
				                <?php if($_product->hasData('presentacion_ml')): ?>
				                    <p class="presentacion"><strong><?php echo $_product->getAttributeText('presentacion_ml'); ?></strong></p>
				                <?php endif; ?>
				                <?php endif ?>
				                <?php if($block->isShow('review')): ?>
				                <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
				                <?php endif ?>
				                <?php if($block->isShow('price')): ?>
				                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
				                <?php endif ?>
				                <?php echo $block->getProductDetailsHtml($_product); ?>

				                <div class="product-item-inner">
				                    <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
				                    	<?php if($block->isShow('addtocart')): ?>
				                        <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<?php 
                                                /* to avoid exception on some product types when calling $stockState */
                                                $productTypesBySkus = $getProductTypesBySkus->execute([$_product->getSku()]);
                                                $productType = $productTypesBySkus[$_product->getSku()];
                                                $sourceManagementAllowed = $isSourceItemManagementAllowedForProductType->execute($productType);
                                                $saleQty = $sourceManagementAllowed ? $stockState->execute($_product->getSku(), 1) : null;
                                            ?> 
                                            <?php if (!$sourceManagementAllowed || ($_product->isSaleable() && $saleQty > 0)): ?>
				                                <?php //$postParams = $block->getAddToCartPostParams($_product); ?>
				                                <!--<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" >
				                                    <button type="submit"
				                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
				                                            class="action tocart primary">
				                                        <i class="fa fa-shopping-cart"></i> <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
				                                    </button>
				                                </a> -->
				                                <?php
												$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()]);
												$postParams = json_decode($postData, true);
												?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]; ?>">
												    <?php echo $block->getBlockHtml('formkey')?>
												    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" class="action tocart primary">
												       <i class="fa fa-shopping-cart"></i> <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												    </button>
												</form>
				                            <?php else: ?>
				                                <?php if (!$sourceManagementAllowed || ($_product->getIsSaleable() && $saleQty > 0)): ?>
				                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
				                                <?php else: ?>
				                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
				                                <?php endif; ?>
				                            <?php endif; ?>
				                        </div>
				                        <?php endif ?>				                        
				                    </div>
				                    <?php endif ?>
				                    <?php if($block->isShow('description')): ?>
				                        <div class="product description product-item-description">
				                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
				                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
				                               class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
				                        </div>
				                    <?php endif; ?>
				                </div>
				            </div>
				        </div>
				        <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
				    <?php endforeach; ?>
				</div>
			</div>
			<?php echo $block->getToolbarHtml() ?>
			<?php if (!$block->isRedirectToCartEnabled()) : ?>
				<script type="text/x-magento-init">
				{
				    "[data-role=tocart-form], .form.map.checkout": {
				        "catalogAddToCart": {}
				    }
				}
				</script>
			<?php endif; ?>
		</div>
	</div>	
<?php endif; ?>
