<?php

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

/** @var $itemHelper Lyracons\QtyIncrement\Helper\Data */
$itemHelper = $this->helper('Lyracons\QtyIncrement\Helper\Data');
$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');
?>
<?php if ($_product->isSaleable()): ?>
<div class="actions actions-mobile">
    <button type="submit"
            title="Add to cart"
            class="action primary tocart"
            id="product-addtocart-button">
        <span><?php /* @escapeNotVerified */ echo __('Comprar') ?></span>
    </button>
    <?php echo $block->getChildHtml('', true) ?>
</div>

<div class="price-box price-final_price price-box_mobile">
    <?php
        $priceModel = $_product->getPriceInfo()->getPrice('regular_price');
        $price = $priceModel->getAmount()->getValue();

        $finalPriceModel = $_product->getPriceInfo()->getPrice('final_price');
        $specialPrice = $finalPriceModel->getAmount()->getValue();

        if (strlen($specialPrice) <= 0 || !($specialPrice < $price)) {
            $specialPrice = $price;
            $price = 0;
        }
    ?>
    <span class="old-price">
        <span class="price">
            <?php
                $price = strlen($specialPrice) > 0 ? $price : $specialPrice;
                if ($price > 0) { echo '$'. number_format($price, 2, ',', ' '); }
           ?>
        </span>
    </span>
    <span class="special-price">
        <span class="price-container price-final_price tax weee">
            <span class="price-wrapper">
                <span class="price">
                    <?php
                        $price = strlen($specialPrice)> 0 ? $specialPrice : $price;
                        echo '$'. number_format($price, 2, ',', ' ');
                    ?>
                </span>
            </span>
        </span>
    </span>
</div>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty">
                <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                <div class="qty-increments qty-increments-mobile">
                    <?php /* @escapeNotVerified */ echo __('Compra mínima: %1 unid.', $itemHelper->getQtyIncrementsByProduct($_product)) ?>
                </div>
            </label>

            <div class="control">
                <div class="qty-minus"> <a class="btn-qty minus" href="#">-</a></div>
                <div class="qty-input">
                    <input type="number"
                           name="qty_visible"
                           id="qty_visible"
                           maxlength="12"
                           value="<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                           disabled
                    />
                    <input type="number"
                        name="qty"
                        id="qty"
                        maxlength="12"
                        value="<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>"
                        title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                        data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        style="display:none;"
                    />
                </div>
                <div class="qty-plus"> <a class="btn-qty plus" href="#">+</a></div>
            </div>
        </div>
        <script type="text/javascript">
        require(['jquery','domReady!'],function($){
            $(".btn-qty").click(function (event) {
                var $button = $(this);
                var oldValue = $button.closest('.control').find("input#qty").val();
                var defaultValue = parseFloat(<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>);
                if ($button.hasClass('plus')) {
                    var newVal = parseFloat(oldValue) + parseFloat(<?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>);
                } else {
                    if (oldValue > defaultValue) {
                        var newVal = parseFloat(oldValue) - <?php echo $itemHelper->getQtyIncrementsByProduct($_product); ?>;
                    } else {
                        newVal = defaultValue;
                    }
                }
                $button.closest('.control').find("input#qty").val(newVal);
                $button.closest('.control').find("input#qty_visible").val(newVal);
                event.preventDefault();
            });
        });
        </script>
        <?php endif; ?>
    </div>
    <div class="actions actions-web">
        <button type="submit"
                title="Add to cart"
                class="action primary tocart"
                id="product-addtocart-button-web">
            <span><?php /* @escapeNotVerified */ echo __('Comprar') ?></span>
        </button>
        <?php echo $block->getChildHtml('', true) ?>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Codazon_AjaxCartPro/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';
        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });
                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>

